# Generated by Django 5.2.17 on 2026-09-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('tmdb_id', 'media_type'), name='unique_tmdb_media'),
        ),
    ]
