# Generated by Django 5.2.17 on 2026-10-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner_url',
            field=models.URLField(blank=True),
        ),
    ]
